--- #YAML:1.0
name:                File-Locate-Harder
version:             0.06
abstract:            when you're determined to use a locate db
license:             ~
author:              
    - Joseph Brenner <doom@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Class::Base:                   0.03
    Data::Dumper:                  0
    File::Locate:                  0.62
    FindBin:                       0
    Hash::Util:                    0
    Symbol:                        0
    Test::Trap:                    v0.0.22
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
